ecomfe/veui-theme-blue

demo/components/Form.vue, demo/components/Select.vue, src/components/Select.js, src/components/button.less, src/components/dialog.less, src/components/field.less, src/components/fieldset.less, src/components/form.less, src/components/select.less, src/components/textarea.less, src/input.less, src/mixins.less, src/variables.less
1. 修改select组件不同尺寸展开icon的大小
2. 同步veui代码到3.15
3. 新增form组件样式
4. 修改button组件小尺寸和禁用状态样式
=> 新增form组件样式

demo/App.vue, demo/cases/Alert.vue, src/components/Alert.js, src/components/alert.less, src/variables/components/alert.less, src/variables/index.less
=> feat(alert): add alert component style (#72)

src/components/badge.less, src/variables/components/badge.less
=> feat(badge): add badge component style (#75)

demo/cases/Badge.vue, src/components/badge.less, src/variables/components/badge.less
=> feat(badge): refine badge component style details (#75)

demo/cases/Pagination.vue, src/components/Pagination.js, src/components/pagination.less, src/variables/components/badge.less, src/variables/components/pagination.less
=> feat(pagination): add pagination component style (#90)

demo/cases/Carousel.vue, demo/cases/index.js, src/components/carousel.less, src/functions.js, src/mixins.less, src/variables/components/carousel.less, src/variables/index.less
=> feat(carousel): add carousel component style (#79)

demo/cases/Collapse.vue, src/components/Accordion.js, src/components/accordion.less, src/components/collapse.less, src/variables/components/collapse.less
=> feat(collapse): add collapse component style (#106)

demo/cases/Button.vue, src/components/Button.js, src/components/button.less, src/variables/components/button.less, src/variables/global.less
=> feat(button): add button component style (#77)

src/components/Button.js
=> feat(button): add button component style & add shape options(#77)

demo/cases/Table.vue, directory.md, src/components/Table.js, src/components/table.less, src/variables/components/table.less
=> fix(table): add table component style (#97)

demo/cases/Grid.vue, demo/cases/Radio.vue, demo/cases/Switch.vue, src/components/radio.less, src/components/switch.less, src/variables/components/radio.less, src/variables/components/switch.less
style(Radio&&switch): change the style of radio component and switch component
=> feat(Radio&&switch): change the style of radio component and switch component (#96) (#93)

demo/cases/Tag.vue, src/components/Tag.js, src/components/tag.less, src/variables/components/tag.less
=> feat(tag): add tag component style(#98)

demo/cases/Button.vue, demo/cases/CheckButtonGroup.vue, demo/cases/Checkbox.vue, demo/cases/CheckboxGroup.vue, demo/cases/Dialog.vue, src/components/Dialog.js, src/components/dialog.less, src/variables/components/button.less, src/variables/components/dialog.less
=> add dialog component(#81)

demo/cases/Button.vue, demo/cases/UI.vue, src/components/Button.js, src/components/button.less, src/variables/components/button.less
=> button样式#77

demo/cases/Menu.vue, src/components/Menu.js, src/components/menu.less, src/variables/components/menu.less
=> add menu component & menu & fix demo(#89)

src/components/Button.js, src/components/CheckButtonGroup.js, src/components/Checkbox.js, src/components/CheckboxGroup.js, src/components/menu.less, src/variables/components/menu.less
button checkbox 默认尺寸修改为s
menu菜单收起展开定位实现ui组件样式
=> fix(menu): add menu component & fix default size (#89#77)

src/components/check-button-group.less, src/variables/components/checkbox.less
=> fix(checkbox): fix check-button-group icon position(#89)

demo/cases/Dialog.vue, demo/cases/Menu.vue, src/components/dialog.less, src/components/menu.less, src/variables/components/menu.less
fix(menu): fix memu & dialog demo(#89#81)
=> fix(menu): fix memu & dialog demo(#89#81)

demo/cases/Dialog.vue, src/components/Menu.js, src/components/dialog.less, src/components/menu.less, src/variables/components/menu.less
menu菜单展开收起点击区域修改& dialog底部按钮高度不限制
=> fix(menu): fix memu &fix  click area & dialog demo(#89#81)

.github/workflows/ci.yml, .gitignore, vue.config.js
=> feat: add ci.yml, deploy to github pages

demo/cases/Autocomplete.vue, demo/cases/Input.vue, demo/cases/InputGroup.vue, src/components/Input.js, src/components/InputGroup.js, src/components/autocomplete.less, src/components/input-group.less, src/components/input.less, src/variables/components/input.less
feat(Input): update Input & InputGroup & autocomplete style
=> feat(Input): update Input & InputGroup & autocomplete style

.husky/verify-commit-msg.js, demo/cases/Select.vue, src/components/Select.js, src/components/select.less, src/variables/components/input.less, src/variables/components/option.less, src/variables/components/select.less, src/variables/global.less
feat(Select): update Select style. #83
=> feat(Select): update Select style. #83

demo/cases/Tree.vue, src/components/tree.less, src/variables/components/tree.less
Change-Id: Id74736529d8f20b4324d4cc345e57a4dc96312a9
=> feat(tree): update tree style. close #103

src/components/DatePicker.js, src/components/date-picker.less, src/variables/components/date-picker.less
Change-Id: Ib445c799bd2f0a9c6384bb77a3530f0b2f896db1
=> feat(DatePicker): update DatePicker style. #78

src/components/calendar.less, src/variables/components/date-picker.less
Change-Id: I66289c54d8cb6f2f8f0ceb2e56a29a9d4d4b8eb0
=> feat(Calendar): update Calendar style. #78
